### ISSUE TITLE
Custom Sign out example needs to be updated

### ISSUE THREAD

**Issue by AnishDe12020** [clerk/docs#10]
I was looking at the [Custom Sign out example](https://docs.clerk.dev/popular-guides/popular-guides-sign-out#custom-sign-out) for React and it is using the `useAuth` hook which doesn't seem to be a part of the `@clerk/nextjs` package (and therefore not a part of `@clerk/react` package as, if I am right, the hooks are extended from the clerk react package). 

This example should be updated to use the `useClerk` hook as that is what returns the `signOut` function.

**Comment by SokratisVidros** [comment]
hi @AnishDe12020. Our latest documentation are about the @clerk/nextjs@3 package. Updating your clerk libraries should fix the issue.

**Comment by AnishDe12020** [comment]
Oh i see, thanks!
