### ISSUE TITLE
Google social login setup guide lacking

### ISSUE THREAD

**Issue by Hades32** [clerk/docs#6]
[This](
https://github.com/clerkinc/docs/blob/2.0.0/reference/social-login-reference/social-login-google.md#configuring-google-social-login) has a few arrows that are not described in the text:
* how to figure out which scopes to set
* where to find the redirect URL
* some tips on how to "publish" the app as Google says they'll somehow verify the app before external users may access it

**Comment by agis** [comment]
Hey @Hades32, thanks for bringing this to our attention! We've pushed a change that hopefully clears up the points you mentioned: https://reference.clerk.dev/reference/social-login-reference/social-login-google.

In short:

- you don't have to set any scopes, we automatically set those that are required for Clerk to work with Google SSO. Setting *additional* scopes that your app may need is possible but completely optional (see [here](https://clerk.dev/docs/how-to/social-login-oauth#configuring-additional-o-auth-scopes))
- the redirect URL can be found in Clerk's Dashboard, if you navigate to your instance and then to **User & Authentication > Social Login**. From there you click _Google_ and in the modal you'll see the "Authorized redirect URI" setting from which you can copy the value
- I think [this](https://support.google.com/cloud/answer/9110914#) is what you're looking for? We'll add a reference link to the guide as well

Do the above answer your questions?

**Comment by agis** [comment]
Closing this for now, if you believe anything is missing, let us know and we'll happily re-open this.
